### ISSUE TITLE
Get user endpoint (without specifying guildId)

### ISSUE THREAD

**Issue by davidlimjh** [tatsuworks/gateway#13]
### Context
An endpoint to retrieve user info without having to specify guild ID for dashboard & framework use

### Required REST Endpoint(s)
```
v1/events/users/{user_id}
```

**Requirements**
- Specify user ID and retrieve all of a user's state info
- Return 404 if no user found

**Expected Input**
- user_id - a user's Discord ID

**Expected Return**
- User info

**Comment by coadler** [comment]
This is very easy now with the Postgres backend.
