### ISSUE TITLE
Error handling messages

### ISSUE THREAD

**Issue by hassieswift621** [tatsuworks/gateway#5]
As a suggestion for error handling, you may want to prefix your errors with the package name to make it easier to debug when you have many microservices running, i.e. "gateway: failed to handle hello message".

This seems to be the common practice employed by the default Go packages such as http and math 👍

**Comment by coadler** [comment]
Do you mean the errors emitted from the `gatewayws` and `manager` packages or for printing to stdout/stderr? For public go packages I think this makes sense but gateway isn't meant to be embedded anywhere so it's less of an issue.

I'm starting to move everything over to use [xerrors](https://godoc.org/golang.org/x/xerrors) so you'll have a stack trace of where the error originated from and how it propagated up the stack, which would also make this less of an issue
